name: tennis-watch

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run scraper
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:   ${{ secrets.CHAT_ID }}
          DEBUG_NOTIFY: "true"
        run: |
          mkdir -p out
          npm start

      - name: Upload screenshots (artifacts)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: out/*.png
          if-no-files-found: ignore
